### ISSUE TITLE
Skip titlebar when scrolling

### ISSUE THREAD

**Issue by jaksatomovic** [KrisKasprzak/Adafruit_ILI9341_Menu#2]
Is it possible to exclude titlebar when we scroll through menu. If we want to exit we would use another button which would be only used to exit or go back

**Comment by KrisKasprzak** [comment]
I could probably add a method that will allow you to skip the title bar. something like MainMenu.setTitleBarExit(true | false);

**Comment by jaksatomovic** [comment]
Great that woul be very helpful. Have you considered maybe to also add some status icons inside titlebar like battery and wifi?
