### ISSUE TITLE
Encoder direction is inverted when scrolling options of char array

### ISSUE THREAD

**Issue by cyberdevnet** [KrisKasprzak/Adafruit_ILI9341_Menu#4]
Hi,

trying the Encoder [example ](https://github.com/KrisKasprzak/Adafruit_ILI9341_Menu/blob/main/Examples/ESP32/ESP32_Menu_EncoderInput/ESP32_Menu_EncoderInput.ino) I noticed that when scrolling for example the C_NAMES options the moving direction is inverted.
```
const char *C_NAMES[46] = {"White", "Black", "Grey", "Blue", "Red", "Green", "Cyan", "Magenta",
                           "Yellow", "Teal", "Orange", "Pink", "Purple", "Lt Grey", "Lt Blue", "Lt Red",
                           "Lt Green", "Lt Cyan", "Lt Magenta", "Lt Yellow", "Lt Teal", "Lt Orange", "Lt Pink", "Lt Purple",
                           "Medium Grey", "Medium Blue", "Medium Red", "Medium Green", "Medium Cyan", "Medium Magenta", "Medium Yellow", "Medium Teal",
                           "Medium Orange", "Medium Pink", "Medium Purple", "Dk Grey", "Dk Blue", "Dk Red", "Dk Green", "Dk Cyan",
                           "Dk Magenta", "Dk Yellow", "Dk Teal", "Dk Orange", "Dk Pink", "Dk Purple"};
```
If i'm on "Black" and I rotate the encoder clockwise it moves to "White" and not to "Grey", same happens with all other examples.

The only difference with your example is that I'm declaring the lenght of the array => const char *C_NAMES[46]

**Comment by KrisKasprzak** [comment]
I just have the code reversed, just need to switch ColorMenu.MoveUP() and ColorMenu.MoveDown().
