### ISSUE TITLE
Leonardo?

### ISSUE THREAD

**Issue by SanderM2** [KrisKasprzak/Adafruit_ILI9341_Menu#5]
The docs say arduino uno is not supported bit it should work on mega.
Will it work on leonardo? I have a leonardo board with adafruit 2.8” capacitive touch screen (ili9341).

i’m not sure why it wouldn’t work on an arduino uno? Maybe because of memory limits??

**Comment by KrisKasprzak** [comment]
If your MCU and display support the Adafruit_ILI9341 driver, this lib should work. I've never tested with Arduino, but I suspect there will be memory limits.
